# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa7423099d241919fb58e7a19c859f768aa29327eb227feaca353e3a931f653bb71ced5be2bbee1376917ea3767b18fd1d3b17d6f7e2260661e9c5b8353e5c7e

test:
  secret_key_base: b92dc026242a7c40a28d67d74cf8fc9306bd5170539834d90b6dc38c0010c62145eab26464f7c225c34dbd463a5055c1c51b4c6282e95aed2a99eb6240f1454e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
